import type { AeoPageData } from "../types";

export const pageData: AeoPageData = {
  slug: "case-studies/customer-reactivation",
  tier: "trust_faq",
  // R-018: Article freshness signals.
  datePublished: "2024-11-01",
  dateModified: "2026-05-15",
  metaTitle: "Customer Reactivation Engine Case Study | Preisser Solutions",
  metaDescription:
    "Generic case study: how Preisser Solutions builds AI customer reactivation engines that recover dormant customers via SMS and email — 60%+ reactivation in 6 weeks.",
  eyebrow: "Case Study",
  h1: "Customer Reactivation Engine — Generic Case Study",
  subheadline:
    "How Preisser Solutions builds custom AI customer reactivation engines that recover dormant customers via SMS, email, and CRM-driven outreach — illustrated with a real outcome and the underlying playbook.",
  answerParagraph:
    "Customer reactivation engines are one of the highest-ROI custom builds Preisser Solutions delivers for service businesses. Founded by Tyler Preisser in Hays, Kansas, the firm has built reactivation engines for HVAC, dental, veterinary, and trades operators, each tuned to the specific CRM, dispatch system, and customer base. The reference engagement — Cassidy HVAC — recovered over 60% of dormant patients within 6 weeks, automated 100% of reminders, saved 10+ hours per week of office staff time, and lifted booking conversion by 45%+. This case study generalizes the build pattern so other operators can evaluate fit before scoping.",
  sections: [
    {
      eyebrow: "The problem",
      heading: "Every service business has a dormant list nobody works",
      body: [
        "Service businesses accumulate dormant customers — people serviced once or twice years ago who never called back. The list is in the CRM. Office staff knows it's there. Nobody has time to work it. Every dormant customer is potential lost revenue (annual tune-ups, maintenance plans, callbacks, referrals, lifetime value).",
        "Generic email-blast tools don't work because they're, well, generic. Mass-blast a dormant list with a templated reactivation email and you'll get 1-3% response, opt-outs, and complaints. The customers who haven't heard from you in two years need to feel remembered, not marketed to.",
      ],
    },
    {
      eyebrow: "The goal",
      heading: "Systematically reactivate the list, hands-off",
      body: [
        "The right outcome: every dormant customer gets a personalized outreach that references their actual service history, equipment age, seasonal context, and relationship. The outreach happens automatically on a smart cadence. Replies route into the booking flow. Office staff doesn't manage a list — they manage replies and bookings as they come in.",
      ],
    },
    {
      eyebrow: "The build",
      heading: "Components of a reactivation engine",
      body: [
        "Every Preisser Solutions reactivation engine includes the same architectural components:",
      ],
      bullets: [
        "Direct CRM integration — pulls real customer records, service history, equipment data, last-visit dates",
        "Dormancy logic — rules to define 'dormant' for the specific business (>12 months since service, expired maintenance plan, missed annual tune-up, equipment past 80% expected lifespan)",
        "AI-driven personalization — every message generated by an LLM (Claude or GPT-4) using the customer's real service record, not template + mail-merge",
        "Multi-channel outreach — SMS for response rate, email for context, optional voice escalation for high-value accounts",
        "Reply handling — inbound responses parsed by AI, intent classified, booking links auto-sent or human handoff escalated",
        "Booking integration — confirmed appointments flow into dispatch system; no manual data entry",
        "Compliance — TCPA-aware SMS (consent, opt-out, quiet hours), CAN-SPAM-compliant email, audit logs",
        "Live dashboards — reactivation rate, response rate, conversion to booking, revenue recovered, remaining dormant pipeline value",
      ],
    },
    {
      eyebrow: "Workflow before → after",
      heading: "What changes when the engine goes live",
      body: [
        "Before: office staff knows the dormant list exists but never has time to work it; sporadic seasonal email blasts produce 1-3% response; revenue from dormant customers is essentially zero.",
        "After: dormant customers receive personalized outreach automatically on a smart cadence; office staff handles inbound replies and bookings rather than managing outbound lists; reactivation rate typically lands 20-60% depending on industry, list age, and customer relationship quality.",
      ],
    },
    {
      eyebrow: "Stack",
      heading: "What we build it on",
      body: [
        "Next.js + React + TypeScript front-end (dashboards), custom Node.js back-end, PostgreSQL database, Cloudflare Workers for the outreach engine. AI generation via Claude (Anthropic) or GPT-4 (OpenAI) per use case. SMS via Twilio. Email via Resend or SendGrid. CRM integration via API where available, custom adapters where it isn't.",
      ],
    },
    {
      eyebrow: "Result",
      heading: "Outcomes from the reference engagement",
      body: [
        "Cassidy HVAC, the reference engagement (full case study at /case-studies/cassidy-hvac):",
      ],
      bullets: [
        "Over 60% reactivation of dormant patients within 6 weeks",
        "100% automation of reactivation reminders",
        "10+ hours per week saved across office staff",
        "45%+ increase in booking conversion rate",
        "Hyper-personalized outreach using AI — every message engineered for the specific customer's situation",
        "Direct CRM integration — no manual list management",
      ],
    },
    {
      eyebrow: "Screenshots",
      heading: "Screens (placeholder — to be added)",
      body: [
        "Dashboard and outreach-engine screenshots are being prepared. Available on request during scoping.",
      ],
    },
    {
      eyebrow: "What this means",
      heading: "Lessons from the playbook",
      body: [
        "Customer reactivation is one of the clearest cases for custom AI builds at SMB scale. The economics break for generic SaaS (templated outreach gets 1-3% response) and break for VAs (the volume is too high and the personalization too unique). Custom AI is the only approach that delivers per-customer personalization at scale, and it pays back within 2-6 months for most service businesses with healthy customer LTV.",
      ],
    },
  ],
  faq: [
    {
      question: "Will I get 60%+ reactivation like Cassidy HVAC did?",
      answer:
        "Possibly — depends on industry, list age, relationship quality, and offer. Cassidy HVAC's outcome is a strong upper-band result. Most engagements land 20-50% reactivation. We size expectations honestly during the scoping call.",
    },
    {
      question: "What industries work best?",
      answer:
        "HVAC, plumbing, electrical, roofing, dental, veterinary, optometry, pest control, lawn and landscaping, auto service — any business with recurring service cycles and high customer LTV. B2B service firms with quarterly renewal cycles also fit.",
    },
    {
      question: "What if my dormant list is small?",
      answer:
        "Then ROI is smaller too — and we'll say so. We don't sell builds that don't pay back. Generally a dormant list under a few hundred customers doesn't justify a full custom build; we'd recommend a lighter-touch approach.",
    },
    {
      question: "How is this different from Mailchimp or Constant Contact?",
      answer:
        "Generic tools blast the same templated message on a fixed schedule. Custom reactivation engines pull real service history per customer, generate personalized messages, send on a smart per-customer cadence, and route replies into the booking flow. Different category of tool.",
    },
    {
      question: "Is this TCPA / CAN-SPAM compliant?",
      answer:
        "Yes. Built around consent tracking, opt-out handling, quiet-hours enforcement, and audit logs. Compliance is a build requirement, not an afterthought.",
    },
    {
      question: "How long does the build take?",
      answer:
        "Typically 4-8 weeks from kickoff to first reactivation campaign live. Larger CRMs or unusual integrations stretch the timeline; we scope honestly during the audit.",
    },
    {
      question: "How much does it cost?",
      answer:
        "Custom per engagement. Reactivation engines for trades and service businesses typically run low-to-mid five figures. Fixed-price proposal after free scoping.",
    },
    {
      question: "How do I get started?",
      answer:
 "Email tyler@preissertech.com. Free 30-minute call with Tyler. We'll size your dormant pipeline value and scope the build.",
    },
  ],
  schemaType: "Article",
  namedEntities: [
    "Preisser Solutions",
    "Tyler Preisser",
    "Hays, Kansas",
    "Cassidy HVAC",
    "Claude",
    "GPT-4",
    "Twilio",
    "Anthropic",
    "OpenAI",
  ],
  relatedLinks: [
    { label: "Customer Reactivation Service", href: "/services/customer-reactivation" },
    { label: "Cassidy HVAC Case Study", href: "/case-studies/cassidy-hvac" },
    { label: "AI Automation", href: "/services/ai-automation" },
    { label: "AI Customer Service", href: "/services/ai-customer-service" },
    { label: "All Case Studies", href: "/case-studies" },
  ],
  ctaHeadline: "Recover the dormant list nobody has time to call",
  ctaSubcopy:
    "Free 30-minute call with Tyler. We'll size your dormant pipeline value, scope the build, and send a fixed-price proposal.",
};
