import type { Metadata } from "next";
import { CaseStudyPage } from "@/components/case-study/CaseStudyPage";
import { BackOfficeStages } from "@/components/case-study/DemoStage/scenes/preisser-back-office/BackOfficeStages";
import { caseStudy } from "@/data/case-studies/preisser-back-office";

const url = `https://preissersolutions.com/case-studies/${caseStudy.slug}`;
// Generated by `node scripts/generate-og-stage.mjs preisser-back-office` from the built end frame.
const ogImage = "/images/case-studies/preisser-back-office-stage-og.jpg";

export const metadata: Metadata = {
  title: caseStudy.metaTitle,
  description: caseStudy.metaDescription,
  alternates: { canonical: url },
  openGraph: {
    siteName: "Preisser Solutions",
    title: caseStudy.metaTitle,
    description: caseStudy.metaDescription,
    url,
    type: "article",
    publishedTime: caseStudy.datePublished,
    modifiedTime: caseStudy.dateModified,
    images: [{ url: ogImage, width: 1200, height: 630, alt: caseStudy.h1 }],
  },
  twitter: {
    card: "summary_large_image",
    title: caseStudy.metaTitle,
    description: caseStudy.metaDescription,
    images: [ogImage],
  },
};

export default function Page() {
  return <CaseStudyPage data={caseStudy} demo={<BackOfficeStages />} />;
}
